[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_i = 1
hook_source = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# [[plugins]]
# repo = 'Shougo/vimfiler.vim'
# depends = 'unite.vim'
# on_if = "isdirectory(bufname('%'))"

# [[plugins]]
# repo = 'ryanoasis/vim-devicons'
# depends = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'Shougo/echodoc.vim'
on_event = 'CompleteDone'
hook_source = '''
  call echodoc#enable()
'''

[[plugins]]
repo = 'Shougo/deoplete-rct'
on_ft = 'ruby'
depends = 'deoplete.nvim'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo ='rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]]
repo = 'rhysd/rust-doc.vim'
on_ft = 'rust'

[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = {n = '<Plug>'}
hook_add = '''
  nmap <silent>j <Plug>(accelerated_jk_gj)
  nmap <silent>k <Plug>(accelerated_jk_gk)
'''

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'vim-operator-user'
on_map = {n = '<Plug>'}
hook_add = '''
  map <silent>sa <Plug>(operator-surround-append)
  map <silent>sd <Plug>(operator-surround-delete)
  map <silent>sr <Plug>(operator-surround-replace)
  map <silent>sc <Plug>(operator-surround-replace)
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_path = '.*'

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_i = 1
on_ft = 'go'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'kana/vim-textobj-indent'
depends = ['vim-textobj-user', 'vim-textobj-function']
on_ft = 'python'

[[plugins]]
repo = 'bps/vim-textobj-python'
depends = ['vim-textobj-user', 'vim-textobj-function']
on_ft = 'python'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'mopp/AOJ.vim'
depends = ['webapi-vim']
