hook_add = '''

" Go
if $GOROOT != ''
   set runtimepath+=$GOROOT/misc/vim
endif

'''

[ftplugin]

go = '''
highlight default link goErr WarningMsg
match goErr /\<err\>/
'''

fish="""
compiler fish
setlocal textwidth=79
setlocal foldmethod=expr
"""
