[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  autocmd VimEnter * nested call octarect#molokai#init()
'''

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
depends = 'scrooloose/nerdtree'
hook_add = '''
map <C-l> <plug>NERDTreeTabsToggle<CR>
if argc() == 0
  let g:nerdtree_tabs_open_on_console_startup = 1
end
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'
depends = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['airblade/vim-gitgutter', 'junegunn/vim-emoji', 'ryanoasis/vim-devicons']
hook_add = '''
  call octarect#lightline#init()
'''

[[plugins]]
repo = 'itchyny/vim-parenmatch'
hook_add = 'let g:loaded_matchparen = 1'

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
  let g:NERDSpaceDelims=1
  let g:NERDDefaultAlign='left'
  let g:NERDCompactSexyComs = 1
  map <silent>co <Plug>NERDCommenterToggle
  filetype plugin on
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
depends = ['junegunn/vim-emoji']

[[plugins]]
repo = 'junegunn/vim-emoji'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'dag/vim-fish'

[[plugins]]
repo = 'dmix/elvish.vim'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-function'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {
  \ '_' : {
    \ 'runner' : 'vimproc',
    \ 'runner/vimproc/updatetime' : 40,
    \ 'outputter' : 'error',
    \ 'outputter/error/success' : 'buffer',
    \ 'outputter/error/error'   : 'quickfix',
    \ 'outputter/buffer/split'  : ':botright 8sp',
  \}
\}
nmap <Leader>r :cclose<CR>:write<CR>:QuickRun -mode n<CR>
'''

[[plugins]]
repo = 'junegunn/limelight.vim'
hook_add = '''
  let g:limelight_conceal_ctermfg = 'DarkGray'
  let g:limelight_conceal_guifg = 'DarkGray' "gvim
  nmap <Leader>l :Limelight!!<CR>
'''
