[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'rhysd/vim-color-spring-night'
hook_add = '''
  let g:spring_night_high_contrast = 1
  let g:spring_night_highlight_terminal = 1
  let g:spring_night_cterm_italic = 1
  autocmd VimEnter * nested call _theme#init('spring-night')
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  call _lightline#init()
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  if executable('rg')
    let g:gitgutter_grep = 'rg --color=never'
  endif
  set signcolumn=yes
  let g:gitgutter_sign_added = '+'
  let g:gitgutter_sign_modified = '*'
  let g:gitgutter_sign_removed = '-'
  nmap gk <Plug>GitGutterPrevHunk
  nmap gj <Plug>GitGutterNextHunk
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'itchyny/vim-parenmatch'
hook_add = '''
  let g:loaded_matchparen = 1
'''

[[plugins]]
repo = 'itchyny/vim-cursorword'
