[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_add = '''
  nnoremap [denite] <Nop>
  nmap <C-u>  [denite]
  nmap <silent> [denite]f :<C-u>Denite file/rec<CR>
'''
hook_post_source = '''
  if executable('rg')
    call denite#custom#var('file/rec', 'command',
          \ [ 'rg', '--files', '--follow', '--hidden', '--glob', '!.git' ])
  endif
  call denite#custom#map('insert', '<Esc>', '<denite:enter_mode:normal>', 'noremap')
  call denite#custom#map('insert', '<C-n>', '<denite:move_to_next_line>', 'noremap')
  call denite#custom#map('insert', '<C-p>', '<denite:move_to_previous_line>', 'noremap')
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_cmd = 'EasyAlign'
hook_add = '''
vnoremap <silent> <Enter> :EasyAlign<cr>
'''

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = {n = '<Plug>'}
hook_add = '''
  nmap <silent>j <Plug>(accelerated_jk_gj)
  nmap <silent>k <Plug>(accelerated_jk_gk)
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_path = '.*'
