[ftplugin]
vim = '''
  setlocal tabstop=2
  setlocal shiftwidth=2
'''

lua = '''
  setlocal tabstop=2
  setlocal shiftwidth=2
'''

json = '''
  setlocal tabstop=2
  setlocal shiftwidth=2
'''

toml = '''
  setlocal tabstop=2
  setlocal shiftwidth=2
'''

yaml = '''
  setlocal tabstop=2
  setlocal shiftwidth=2
'''

make = '''
  setlocal tabstop=4
  setlocal shiftwidth=4
  setlocal noexpandtab
'''

html = '''
  setlocal tabstop=2
  setlocal shiftwidth=2
'''

javascript = '''
  setlocal tabstop=2
  setlocal shiftwidth=2
'''

typescript = '''
  setlocal tabstop=2
  setlocal shiftwidth=2
'''

sass = '''
  setlocal tabstop=4
  setlocal shiftwidth=4
  setlocal noexpandtab
'''

go = '''
  setlocal tabstop=4
  setlocal shiftwidth=4
  setlocal noexpandtab
'''

c = '''
  setlocal tabstop=2
  setlocal shiftwidth=2
'''

cpp = '''
  setlocal tabstop=2
  setlocal shiftwidth=2
'''
