[[plugins]]
repo = 'junegunn/fzf.vim'
on_map = ':<C-u>Fzf'
hook_source = "call rc#source_rc('plugin/fzf.rc.vim')"
hook_add = '''
  let g:fzf_command_prefix = 'Fzf'
  nmap <silent> <Leader>df :<C-u>FzfGitFiles<CR>
  nmap <silent> <Leader>dF :<C-u>FzfFiles<CR>
  nmap <silent> <Leader>dg :<C-u>FzfRg<CR>
  nmap <silent> <Leader>db :<C-u>FzfBuffers<CR>
  nmap <silent> <Leader>dc :<C-u>FzfColors<CR>
  nmap <silent> <Leader>de :<C-u>FzfEmoji<CR>
'''

[[plugins]]
repo = 'junegunn/fzf'
merged = 0
build = './install --bin'
on_source = 'fzf.vim'

[[plugins]]
repo = 'junegunn/vim-emoji'
on_source = 'fzf.vim'

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd='Deol'
hook_add = '''
  nnoremap <silent> <Leader>tt :<C-u>Deol -no-start-insert<CR>
  " nnoremap <silent> <Leader>tf :<C-u>Deol zsh -split=floating<CR>
  nnoremap <silent> <Leader>tq :<C-u>call deol#kill_editor()<CR>
  function! s:open_floating() abort
    let winwidth  = &columns > 180 ? float2nr(&columns / 2) : 90
    let wincol    = &columns > winwidth ? (&columns - winwidth) / 2 : 0
    let winheight = &lines > 40 ? float2nr(&lines * 5 / 8) : 24
    let winrow    = &lines > winheight ? (&lines - winheight) / 2 : 0
    execute 'Deol -split=floating -no-start-insert'
        \ '-winheight=' . winheight
        \ '-winwidth=' . winwidth
        \ '-winrow=' . winrow
        \ '-wincol=' . wincol
  endfunction
  nnoremap <silent> <Leader>tf :<C-u>call <SID>open_floating()<CR>
'''
hook_source = '''
  " Normal mode (I cannot do VIM in VIM anymore)
  tnoremap <C-j><C-j> <C-\><C-n>
'''

[plugins.ftplugin]
deol = '''
setlocal signcolumn=no
'''

[[plugins]]
repo = 'Shougo/junkfile.vim'
on_source = 'denite.nvim'
hook_add = '''
  nnoremap <silent> <Leader>dj :<C-u>Denite junkfile:new junkfile<CR>
'''

#-----------------------------------------------------------
# Edit
#-----------------------------------------------------------

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'scrooloose/nerdcommenter'
on_map = '<Plug>NERDCom'
hook_add = '''
  let g:NERDSpaceDelims = 1
  let g:NERDDefaultAlign = 'left'
  let g:NERDCompactSexyComs = 1
  nmap <silent>co <Plug>NERDCommenterToggle
  vmap <silent>co <Plug>NERDCommenterToggle
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_cmd = 'EasyAlign'
hook_add = '''
  vnoremap <silent><Enter> :EasyAlign<cr>
'''

[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = { n = '<Plug>' }
hook_add = '''
  let g:accelerated_jk_acceleration_table = [3,5,8,12,16,20,24]
  nmap <silent>j <Plug>(accelerated_jk_gj)
  nmap <silent>k <Plug>(accelerated_jk_gk)
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'itchyny/vim-cursorword'
on_event = ['BufRead']

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_path = '.*'

[[plugins]]
repo = 'luochen1990/rainbow'
on_ft = ['go', 'javascript', 'python', 'vim', 'html', 'css', 'scss']
hook_source = '''
  let g:rainbow_active = 1
  let g:rainbow_conf = {
      \ 'guifgs': ['mediumorchid1', 'deepskyblue1', 'springgreen', 'yellow', 'darkorange', 'firebrick'],
      \ }
'''

#-----------------------------------------------------------
# Language / FileType
#-----------------------------------------------------------

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_source = '''
  let g:vim_markdown_folding_disabled = 1
  nnoremap <LocalLeader>t :<C-u>TableFormat<CR>
  nnoremap <LocalLeader>i :<C-u>HeaderIncrease<CR>
  nnoremap <LocalLeader>d :<C-u>HeaderDecrease<CR>
'''

[[plugins]]
repo = 'godlygeek/tabular'
on_source = 'vim-markdown'

[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_source = 'vim-markdown'

[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown', 'asciidoc']
hook_source = '''
  nnoremap <LocalLeader>r :<C-u>PrevimOpen<CR>
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_source = 'previm'

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = 'terraform'
hook_source = '''
  " let g:terraform_fold_sections = 1
  let g:terraform_fmt_on_save = 1
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ["html", "eruby", "htmldjango"]

[[plugins]]
repo = 'elixir-editors/vim-elixir'
on_ft = 'elixir'
