#-----------------------------------------------------------
# Terminal
#-----------------------------------------------------------

[[plugins]]
repo = 'akinsho/toggleterm.nvim'
on_map = { n = '<Leader>t' }
hook_source = '''
  lua require('plugins.toggleterm')
'''

#-----------------------------------------------------------
# Edit
#-----------------------------------------------------------

[[plugins]]
repo = 'scrooloose/nerdcommenter'
on_map = '<Plug>NERDCom'
hook_add = '''
  let g:NERDSpaceDelims = 1
  let g:NERDDefaultAlign = 'left'
  let g:NERDCompactSexyComs = 1
  nmap <silent>co <Plug>NERDCommenterToggle
  vmap <silent>co <Plug>NERDCommenterToggle
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_cmd = 'EasyAlign'
hook_add = '''
  vnoremap <silent><Enter> :EasyAlign<cr>
'''

[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = { n = '<Plug>' }
hook_add = '''
  let g:accelerated_jk_acceleration_table = [3,5,8,12,16,20,24]
  nmap <silent>j <Plug>(accelerated_jk_gj)
  nmap <silent>k <Plug>(accelerated_jk_gk)
'''

[[plugins]]
repo = 'windwp/nvim-autopairs'
on_event = ['InsertEnter']
hook_source = '''
lua require('plugins.nvim-autopairs')
'''

[[plugins]]
repo = 'itchyny/vim-cursorword'
on_event = ['BufNewFile', 'BufRead']

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_path = '.*'

#-----------------------------------------------------------
# Language / FileType
#-----------------------------------------------------------

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_source = '''
  let g:vim_markdown_folding_disabled = 1
  nnoremap <LocalLeader>t :<C-u>TableFormat<CR>
  nnoremap <LocalLeader>i :<C-u>HeaderIncrease<CR>
  nnoremap <LocalLeader>d :<C-u>HeaderDecrease<CR>
'''

[[plugins]]
repo = 'godlygeek/tabular'
on_source = 'vim-markdown'

[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_source = 'vim-markdown'

[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown', 'asciidoc']
hook_source = '''
  nnoremap <LocalLeader>r :<C-u>PrevimOpen<CR>
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_source = 'previm'

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = 'terraform'
hook_source = '''
  " let g:terraform_fold_sections = 1
  let g:terraform_fmt_on_save = 1
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ["html", "eruby", "htmldjango"]
