[ftplugin]
html = '''
setlocal tabstop=2
setlocal shiftwidth=2
'''

yaml = '''
setlocal tabstop=2
setlocal shiftwidth=2
'''

make = '''
setlocal tabstop=4
setlocal shiftwidth=4
setlocal noexpandtab
'''

sass = '''
setlocal tabstop=4
setlocal noexpandtab
'''
