[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['vim-gitgutter', 'vim-gitbranch', 'vim-devicons']
hook_add = "call rc#source_rc('plugin/lightline.rc.vim')"

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
" Use block as sign
let g:gitgutter_sign_added                   = '█'
let g:gitgutter_sign_modified                = '█'
let g:gitgutter_sign_removed                 = '█'
let g:gitgutter_sign_removed_first_line      = '█'
let g:gitgutter_sign_removed_above_and_below = '█'
let g:gitgutter_sign_modified_removed        = '█'
" Keymappings for hunk jumping
nmap <silent> [c <Plug>(GitGutterPrevHunk)
nmap <silent> ]c <Plug>(GitGutterNextHunk)
nmap <silent> <Leader>ggd :GitGutterPreviewHunk<CR>
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'itchyny/vim-gitbranch'

[[plugins]]
repo = 'itchyny/vim-parenmatch'
hook_add = '''
  let g:loaded_matchparen = 1
  let g:parenmatch_highlight = 0
  highlight link ParenMatch MatchParen
'''

[[plugins]]
repo = 'rhysd/vim-color-spring-night'
merged = 0
hook_add = '''
  let g:spring_night_high_contrast = 1
  let g:spring_night_highlight_terminal = 1
  let g:spring_night_cterm_italic = 1
'''

[[plugins]]
repo = 'hardcoreplayers/oceanic-material'
merged = 0
hook_add = '''
  let g:oceanic_material_allow_bold = 1
  let g:oceanic_material_allow_italic = 1
'''

