[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = ['BufNewFile', 'BufRead']
hook_source = '''
lua require('plugins.lsp')
'''

[[plugins]]
repo = 'kabouzeid/nvim-lspinstall'
on_source = 'nvim-lspconfig'

[[plugins]]
repo = 'hrsh7th/nvim-compe'
on_event = ['InsertEnter']
depends = ['compe-tabnine']
hook_source = '''
set completeopt=menuone,noselect
lua require('plugins.nvim-compe')
'''

[[plugins]]
repo = 'tzachar/compe-tabnine'
build = './install.sh'
