[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = ['BufNewFile', 'BufRead']
hook_source = '''
lua require('plugin.lsp')
'''

[[plugins]]
repo = 'hrsh7th/nvim-compe'
on_source = 'nvim-lspconfig'
hook_source = '''
set completeopt=menuone,noselect
lua require('plugin.nvim-compe')
'''

[[plugins]]
repo = 'kabouzeid/nvim-lspinstall'
on_source = 'nvim-lspconfig'
