[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = ['BufNewFile', 'BufRead']
hook_source = '''
lua require('plugins.lsp')
'''

[[plugins]]
repo = 'kabouzeid/nvim-lspinstall'
on_source = 'nvim-lspconfig'

[[plugins]]
repo = 'hrsh7th/nvim-compe'
on_event = ['InsertEnter']
depends = ['compe-tabnine']
hook_source = '''
set completeopt=menuone,noselect
lua require('plugins.nvim-compe')
'''

[[plugins]]
repo = 'tzachar/compe-tabnine'
build = './install.sh'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = ['BufNewFile', 'BufRead']
# NOTE: Make sure all plugins of nvim-treesitter are listed here
depends = ['nvim-ts-rainbow']
hook_source = '''
lua require('plugins.nvim-treesitter')
'''
hook_post_update = 'TSUpdate'

[[plugins]]
repo = 'p00f/nvim-ts-rainbow'
