[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
on_lua = 'telescope'
hook_add = 'lua require("plugins.telescope").set_keymaps()'
hook_source = 'lua require("plugins.telescope").init()'
depends = [
  'popup.nvim',
  'plenary.nvim',
  'nvim-web-devicons',
  'telescope-symbols.nvim',
  'telescope-menu.nvim',
  'telescope-fzf-native.nvim',
]

[[plugins]]
repo = 'nvim-lua/popup.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'nvim-telescope/telescope-symbols.nvim'

[[plugins]]
repo = 'octarect/telescope-menu.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope-fzf-native.nvim'
build = 'make'
