[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = ['popup.nvim', 'plenary.nvim', 'nvim-web-devicons', 'telescope-symbols.nvim']
on_lua = 'telescope'
hook_add = 'lua require("plugins.telescope").set_keymaps()'
hook_source = 'lua require("plugins.telescope").init()'

[[plugins]]
repo = 'nvim-lua/popup.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'nvim-telescope/telescope-symbols.nvim'
