[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = ['BufNewFile', 'BufRead']
# NOTE: Make sure all plugins of nvim-treesitter are listed here
depends = ['nvim-ts-rainbow']
hook_source = '''
lua require('plugins.nvim-treesitter')
'''
hook_post_update = 'TSUpdate'

[[plugins]]
repo = 'p00f/nvim-ts-rainbow'

