[ftplugin]
html = '''
setlocal tabstop=4
setlocal shiftwidth=4
'''

sass = '''
setlocal tabstop=4
setlocal noexpandtab
'''

make = '''
setlocal noexpandtab
setlocal tabstop=4
setlocal shiftwidth=4
'''
