[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = "call util#source_rc('plugins/denite.rc.vim')"
hook_add = '''
  nnoremap [denite] <Nop>
  nmap <C-u>  [denite]
  nmap <silent> [denite]f :<C-u>Denite file/rec<CR>
  nmap <silent> [denite]b :<C-u>Denite buffer<CR>
  nmap <silent> [denite]l :<C-u>Denite line<CR>
  nmap <silent> [denite]g :<C-u>Denite grep<CR>
  nmap <silent> [denite]m :<C-u>Denite menu<CR>
  nmap <silent> [denite]e :<C-u>Denite emoji<CR>
'''

[[plugins]]
repo = 'junegunn/vim-emoji'
on_source = 'denite.nvim'

[[plugins]]
repo = 'pocari/vim-denite-emoji'
on_source = 'vim-emoji'

[[plugins]]
repo = 'Shougo/deol.nvim'
on_source = 'denite.nvim'
hook_add = '''
  nnoremap <silent> [Space]t :<C-u>Deol zsh -no-start-insert<CR>
'''
hook_source = '''
tnoremap <C-j><C-j> <C-\><C-n>
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = [ 'context_filetype.vim' ]
on_i = 1
hook_source = '''
  call deoplete#enable()
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
on_source = 'deoplete.nvim'
rev = 'next'
build = 'bash install.sh'
on_i = 1
hook_source = '''
  " Required for operations modifying multiple buffers like rename
  set hidden
  let g:LanguageClient_serverCommands = {
  \ 'ruby': [ 'solargraph', 'stdio' ],
  \ 'python': ['pyls'],
  \ }
  let g:LanguageClient_loadSettings = 1
  let g:LanguageClient_settingsPath = g:conf_dir . '/rc/plugins/lsp_settings.json'
  nnoremap [Space]l :call LanguageClient_contextMenu()<CR>
  vnoremap [Space]l :call LanguageClient_contextMenu()<CR>
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = [ 'vimproc.vim' ]
on_cmd = 'QuickRun'
hook_add = '''
  nnoremap [Space]r :cclose<CR>:write<CR>:QuickRun -mode n<CR>
  vnoremap [Space]r :QuickRun -mode n<CR>
'''
hook_source = '''
  let g:quickrun_config = {
        \ '_': {
        \   'runner': 'vimproc',
        \   'runner/vimproc/updatetime': 100,
        \   'outputter': 'error',
        \   'outputter/error/success': 'buffer',
        \   'outputter/error/error': 'quickfix',
        \   'outputter/buffer/split': ':botright 8sp',
        \ },
        \ }
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

########################################
# Edit
########################################

[[plugins]]
repo = 'ujihisa/neco-look'
on_source = 'deoplete.nvim'

[[plugins]]
repo = 'scrooloose/nerdcommenter'
on_map = '<Plug>NERDCom'
hook_add = '''
  let g:NERDSpaceDelims=1
  let g:NERDDefaultAlign='left'
  let g:NERDCompactSexyComs = 1
  nmap <silent>co <Plug>NERDCommenterToggle
  vmap <silent>co <Plug>NERDCommenterToggle
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_cmd = 'EasyAlign'
hook_add = '''
vnoremap <silent> <Enter> :EasyAlign<cr>
'''

[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = { n = '<Plug>' }
hook_add = '''
  nmap <silent>j <Plug>(accelerated_jk_gj)
  nmap <silent>k <Plug>(accelerated_jk_gk)
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_path = '.*'

########################################
# Language / Filetype
########################################

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = 'terraform'
hook_source = '''
  let g:terraform_fold_sections = 1
  let g:terraform_fmt_on_save = 1
'''

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = 'markdown'
depends = [ 'vim-markdown-quote-syntax' ]
hook_source = '''
  let g:vim_markdown_folding_disabled = 1
'''
[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'othree/es.next.syntax.vim'
depends = [ 'yajs.vim' ]
on_ft = 'javascript'

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
depends = [ 'yajs.vim' ]
on_ft = 'javascript'

[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = 'yaml'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'
hook_source = '''
  let g:user_emmet_leader_key ='<C-Y>'
  let g:user_emmet_complete_tag = 1
  let g:user_emmet_settings = {
  \ 'lang': 'ja',
  \ 'html': {
  \   'filters': 'html',
  \ },
  \ 'css': {
  \   'filters': 'fc',
  \ },
  \}
'''
